from enum import Enum

class Operation(Enum):
    
    FIND_SUCCESSOR = 1
    FIND_PREDECESSOR = 2
    NOTIFY = 3
    GET_SUCCESSOR = 4
    GET_PREDECESSOR = 5
    CLOSEST_PRECEDING_FINGER = 6
    CHECK_PREDECESSOR = 7
    JOIN = 8
    SELECT_LEADER = 9
    NOTIFY_LEADER = 10
    BROADCAST_DISCOVER = 11
    GET_LEADER = 12
    STORE_DATA = 13
    pass
